# Generated by Django 5.2.16 on 2026-08-18 13:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g. "Casual Day"', max_length=100)),
                ('dog_count', models.PositiveSmallIntegerField(choices=[(1, '1 dog'), (2, '2 dogs')], default=1, help_text='Which pricing grid this plan appears in')),
                ('photo', models.ImageField(blank=True, upload_to='pricing/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period_label', models.CharField(help_text='e.g. "1 Day", "10 Days"', max_length=30)),
                ('tone', models.CharField(choices=[('blue', 'Blue'), ('gold', 'Gold'), ('pink', 'Pink'), ('mint', 'Mint')], default='blue', max_length=10)),
                ('features_text', models.TextField(help_text='One feature per line.')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('hours_weekday', models.CharField(blank=True, help_text='e.g. "Mon–Fri: 7am–6pm"', max_length=100)),
                ('hours_weekend', models.CharField(blank=True, help_text='e.g. "Sat–Sun: 8am–4pm"', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Puppy Specialist', max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('bio', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
