# Generated by Django 5.2.16 on 2026-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='period_label_2',
            field=models.CharField(blank=True, help_text='e.g. "Session" — only used when Price 2 is set.', max_length=30),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional second price — fill this in to show a split two-price card (e.g. Half-Day vs Session) instead of the single price above.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_2_caption',
            field=models.CharField(blank=True, help_text='Short caption under the second price.', max_length=120),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_caption',
            field=models.CharField(blank=True, help_text='Short caption under this price, e.g. "Ideal for shorter visits". Only shown when Price 2 is also set.', max_length=120),
        ),
    ]
