# Generated by Django 5.2.16 on 2026-09-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pricingplan_period_label_2_pricingplan_price_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Leave blank to show only on the main Gallery page. Set this to also show the photo on that service's own gallery.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.service'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='period_label_3',
            field=models.CharField(blank=True, help_text='Only used when Price 3 is set.', max_length=30),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional third price — only used when Price 2 is also set, for a three-way split (e.g. Half-Day / Session / Full Week).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_3_caption',
            field=models.CharField(blank=True, help_text='Short caption under the third price.', max_length=120),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Which service this plan's prices belong to. Leave blank to show on every service's page (legacy behaviour).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='website.service'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional second price — fill this in to show a split price card (e.g. Half-Day vs Session) instead of the single price above.', max_digits=8, null=True),
        ),
    ]
