# Generated by Django 5.2.16 on 2026-09-26 06:55

from django.db import migrations


def assign_to_daycare(apps, schema_editor):
    """All pricing plans predate the per-service field and are Daycare-specific
    (their names/content and the section headings ("Daycare Plans for ...") only
    ever referred to daycare) — point every existing plan at that service."""
    Service = apps.get_model("website", "Service")
    PricingPlan = apps.get_model("website", "PricingPlan")
    daycare = Service.objects.filter(slug="dog-daycare").first()
    if daycare is not None:
        PricingPlan.objects.filter(service__isnull=True).update(service=daycare)


def reverse(apps, schema_editor):
    PricingPlan = apps.get_model("website", "PricingPlan")
    PricingPlan.objects.all().update(service=None)


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_galleryimage_service_pricingplan_period_label_3_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_to_daycare, reverse),
    ]
