# Generated by Django 5.2.16 on 2026-09-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_assign_pricing_plans_to_daycare'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tagline_1dog_gold',
            field=models.CharField(blank=True, help_text='Gold-highlighted part of the "1 dog" pricing heading. Defaults to "Save More!" when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline_1dog_plain',
            field=models.CharField(blank=True, help_text='Plain part of the "1 dog" pricing heading. Defaults to "Give Your Pup More Play &" when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline_2dogs_gold',
            field=models.CharField(blank=True, help_text='Gold-highlighted part of the "2 dogs" pricing heading. Defaults to "Twice the Happiness!" when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline_2dogs_plain',
            field=models.CharField(blank=True, help_text='Plain part of the "2 dogs" pricing heading. Defaults to "Two Pups," when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline_3dogs_gold',
            field=models.CharField(blank=True, help_text='Gold-highlighted part of the "3 dogs" pricing heading. Defaults to "Triple the Tail Wags!" when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline_3dogs_plain',
            field=models.CharField(blank=True, help_text='Plain part of the "3 dogs" pricing heading. Defaults to "Three Pups," when blank.', max_length=80),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='dog_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 dog'), (2, '2 dogs'), (3, '3 dogs')], default=1, help_text='Which pricing grid this plan appears in'),
        ),
    ]
