# Generated by Django 5.2.16 on 2026-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_service_tagline_1dog_gold_service_tagline_1dog_plain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile',
            field=models.CharField(blank=True, help_text='e.g. "0412 345 678"', max_length=30),
        ),
    ]
