# Generated by Django 5.2.16 on 2026-09-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_legalpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('dog_name', models.CharField(max_length=100)),
                ('food_allergies', models.TextField(blank=True, help_text='Any foods, ingredients or treats this dog should avoid.')),
                ('instagram_handle', models.CharField(blank=True, help_text='Optional — shared only if the owner opts in to being tagged on Instagram Stories.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
